import EvalKit
import Foundation
import XCTest

/// Pins the vDSP mel frontend against mels dumped from NeMo's own
/// preprocessor (tools/convert/refs/, regenerated by the ref-dump snippet in
/// that directory's history). If these fixtures are absent the tests skip —
/// they exist on machines that have run the conversion pipeline.
final class MelFrontendTests: XCTestCase {
    struct Ref: Codable {
        let id: String
        let samples: Int
        let mel_bins: Int
        let mel_frames: Int
    }

    static let refsDir = URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent()   // MimiTests
        .deletingLastPathComponent()   // Tests
        .deletingLastPathComponent()   // repo root
        .appendingPathComponent("tools/convert/refs")

    func loadRefs() throws -> [Ref] {
        let manifest = Self.refsDir.appendingPathComponent("manifest.json")
        guard FileManager.default.fileExists(atPath: manifest.path) else {
            throw XCTSkip("no reference mels — run the ref dump in tools/convert first")
        }
        return try JSONDecoder().decode([Ref].self, from: Data(contentsOf: manifest))
    }

    func floats(_ name: String) throws -> [Float] {
        let data = try Data(contentsOf: Self.refsDir.appendingPathComponent(name))
        return data.withUnsafeBytes { Array($0.bindMemory(to: Float.self)) }
    }

    func testMelMatchesNeMo() throws {
        let frontend = MelFrontend()
        for ref in try loadRefs() {
            let audio = try floats("\(ref.id).audio.f32")
            XCTAssertEqual(audio.count, ref.samples)
            let expected = try floats("\(ref.id).mel.f32")   // [bins x frames] row-major

            let mel = frontend.mel(of: audio)
            XCTAssertEqual(mel.count, ref.mel_bins)
            XCTAssertEqual(mel[0].count, ref.mel_frames, "frame count must match NeMo exactly")

            // Normalized units, so an absolute tolerance is meaningful. The
            // mean abs difference is the contract; a loose max catches any
            // localized blowup the mean would smear over.
            var totalAbsDiff = 0.0
            var maxAbsDiff: Float = 0
            for m in 0..<ref.mel_bins {
                for t in 0..<ref.mel_frames {
                    let d = abs(mel[m][t] - expected[m * ref.mel_frames + t])
                    totalAbsDiff += Double(d)
                    maxAbsDiff = max(maxAbsDiff, d)
                }
            }
            let meanAbsDiff = totalAbsDiff / Double(ref.mel_bins * ref.mel_frames)
            XCTAssertLessThan(meanAbsDiff, 0.01, "\(ref.id): mean abs diff \(meanAbsDiff)")
            XCTAssertLessThan(maxAbsDiff, 0.35, "\(ref.id): max abs diff \(maxAbsDiff)")
        }
    }
}
